spring:
  application:
    name: ms-pedido

  profiles:
    active: "local"

  datasource:
    url: jdbc:mysql://${DB_HOST}}/pedido
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 10
          initial-interval: 1000
          multiplier: 2