spring:
  application:
    name: ms-pedido

  profiles:
    active: "local"

  datasource:
    url: jdbc:mysql://${DB_HOST}}/pedido
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    stream:
      bindings:
        pedidoConsumer-in-0:
          destination: pedidoQueue
          group: criar
          content-type: application/json

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}