server:
  port: 8082

spring:
  application:
    name: ms-pedido

  profiles:
    active: "local"

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 10
          initial-interval: 5000
          multiplier: 2

cliente:
  url: http://localhost:8080

produto:
  url: http://localhost:8081