server:
  port: 8082

spring:
  sql:
    init:
      mode: always

  application:
    name: ms-pedido

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 10
          initial-interval: 5000
          multiplier: 2
    virtual-host: ${RABBITMQ_USER}

cliente:
  url: http://localhost:8080

produto:
  url: http://localhost:8081